exclude: '.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
  - repo: local
    hooks:
      - id: format
        name: iSort Black and autoFlake your code [format].
        entry: make format
        language: system
        stages: [commit]
      - id: formatdiff
        name: iSort Black and autoFlake your code [diff].
        entry: make formatdiff
        language: system
        stages: [push]
