exclude: '.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
  - repo: local
    hooks:
      - name: iSort Black and autoFlake your python code
        id: formatting
        entry: make format
        language: system
        stages: [commit, push]
